Hw
EvgeniyFedorchenko/Homework2.3 pull request #1
Opened 2023-11-08 08:05 UTC by Enot393

2023-11-08 12:08 UTC, OlgaLugacheva requested changes

2023-11-08 12:08 UTC, OlgaLugacheva commented on src/main/java/com/calculator/Calculator/CalcController.java
> +    @RequestMapping(path = "calculator/minus")
маппинг сделать GetMapping("/minus")
так как общий маппинг уже определен 
в остальных эндпоинтах аналогично

2023-11-09 09:03 UTC, Enot393 commented on src/main/java/com/calculator/Calculator/CalcController.java
> +            @RequestParam(value = "num1", required = false) String num1,
Да, заменить на Integer - действительно удобнее получается
А requierd и проверка на null нужны чтоб нормальный текст об ошибке вернуть если вот такой адрес вызвать: http://localhost:8080/calculator/minus?num1=5

2023-11-09 09:40 UTC, Enot393 commented on src/main/java/com/calculator/Calculator/CalcController.java
> +    @RequestMapping(path = "calculator/minus")
Действительно

2023-12-30 03:51 UTC, merged